server:
  port: 8080
  servlet:
    #基础路径
    context-path: /outfit_match
spring:
  application:
    name: cloth-mangmement-server
  ##数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloth_fit?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
##redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: ''
    database: 0
    jedis:
      pool:
        ##连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ##连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ##连接池中的最大空闲连接
        max-idle: 8
        ##连接池中的最小空闲连接
        min-idle: 0
    ##连接超时时间（毫秒）
    connect-timeout: 30000
  mvc:
    static-path-pattern: /static/**

#mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: cn.yz.springcloud.entities    # 所有Entity别名类所在包

